table Orders
	lineageTag: ab019228-85b7-4ee9-8cf5-9ad3d01155b8

	measure ProfitPercent = SUM(Orders[Profit])/SUM(Orders[Sales])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 59f0d631-b38d-4684-9152-fea1c52bd2c9

	column 'Order ID'
		dataType: string
		lineageTag: 2e303025-6ee0-46d2-ba75-0718bab4cd48
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c9719190-0f56-4524-8c37-9d4fac5c241d
		summarizeBy: none
		sourceColumn: Order Date

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ae276126-b880-4067-a8d0-9f477aa377eb
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 55e0fa10-3493-4383-9b2d-4845a1e1eefa
			defaultHierarchy: LocalDateTable_5b19b158-6918-48b3-a624-1329c4ed748e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 56500e74-6411-4f26-84a7-e12b3bec3f31
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: a22c6fa4-2535-475c-8b19-d37a717fb644
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 4aea4ecb-df2c-4f6c-aaef-1db6408a49d3
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: c7fe9511-46b9-4785-a489-c55a40371ff3
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: f721620d-be30-46aa-85a9-3499d665498e
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 7a9b20f5-3bda-4699-9179-91cf608beff2
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: ef14cc6a-5f42-44d6-885c-fa4141e2f1b7
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 3ca988d2-53a8-4ed0-a5b6-8e098add4b8d
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: d76fe8e0-22f5-4dc7-b11a-9bdf7ac653d1
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 24f7e011-3457-475c-8ae4-2e78877732ed
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 939b3ace-c6d4-40a4-a750-6e1db98a9bab
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: f126d8cd-712c-4bcc-8f3e-c1982132628e
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 4cb19a15-94d5-4906-b85f-46871aaf2f2d
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 06080343-d072-47ac-a3ce-ca1899a50dd6
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 2cc07818-13ed-4d8d-ab30-f9118525b115
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: fa67980e-f404-47ae-9c88-d3b01b21f4e0
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\nirma\Downloads\Sample - Superstore.csv\Sample - Superstore.xlsx"), null, true),
				    #"Sample - Superstore_Sheet" = Source{[Item="Sample - Superstore",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Sample - Superstore_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Order ID", "Order Date", "Ship Date", "Ship Mode", "Customer ID", "Customer Name", "Segment", "Country", "City", "State", "Postal Code", "Region", "Category", "Sub-Category", "Product Name", "Sales", "Quantity", "Discount", "Profit"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

